name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - README.md
      - .vscode/**
      - .gitignore
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - README.md
      - .vscode/**
      - .gitignore
  
  # allows for running the workflow manually from the actions tab
  workflow_dispatch:

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:	
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: set up qemu
        uses: docker/setup-qemu-action@v1
      -
        name: set up docker buildx
        uses: docker/setup-buildx-action@v1
      -
        name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: buld and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./CarvedRock.Api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/carvedrockapi:latest, ${{ secrets.DOCKERHUB_USERNAME }}/carvedrockapi:${{ github.run_number }}
